openapi: 3.0.3
info:
  description: 'Spec for the FIWARE Apollo'
  version: 0.0.1
  title: FIWARE Apollo
  contact:
    email: stefan.wiedemann@fiware.org
tags:
  - name: Notification
    description: Endpoints for receiving notification

paths:
  '/notification':
    post:
      tags:
        - Notification
      description: Endpoint to receive all notifications
      operationId: receiveNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '204':
          description: Notification received.
components:
  schemas:
    LdContext:
      type: object
    Notification:
      type: object
      properties:
        id:
          type: string
          format: URI
        type:
          type: string
          enum:
            - Notification
        subscriptionId:
          type: string
          format: URI
        notifiedAt:
          type: string
          format: date-time
        data:
          type: array
          items:
            $ref: '#/components/schemas/NotifiedEntity'
    ProblemDetails:
      type: object
      description: Information about the occured error.
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
      required:
        - type
    NotifiedEntity:
      type: object
      properties:
        '@context':
          $ref: '#/components/schemas/LdContext'
        id:
          type: string
          format: uri
      additionalProperties:
        type: object