openapi: 3.0.3
info:
  description: 'This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders'
  version: latest
  title: ETSI ISG CIM / NGSI-LD API
  contact:
    email: NGSI-LD@etsi.org
externalDocs:
  description: Find out more about the ETSI ISG Context Information Management
  url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
tags:
  - name: ETSI
    description: European Telecommunications Standards Institute
    externalDocs:
      description: Find out more
      url: 'http://www.etsi.org'
  - name: CIM
    description: Context Information Management
    externalDocs:
      description: Find out more
      url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
  - name: JSON-LD
    description: JSON for Linked Data
    externalDocs:
      description: Find out more
      url: 'https://json-ld.org/'
  - name: NGSI-LD API
    description: API defined by the ETSI ISG CIM
    externalDocs:
      description: Preliminary Specification
      url: 'http://www.etsi.org/deliver/etsi_gs/CIM/001_099/004/01.01.01_60/gs_CIM004v010101p.pdf'
paths:
  '/entities/':
    parameters:
      - $ref: '#/components/parameters/tenantHeader'
    post:
      description: Create a new Entity within an NGSI-LD system
      operationId: createEntity
      tags:
        - Context Information
        - Entities
      requestBody:
        required: true
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '201':
          description: Created. Contains the resource URI of the created Entity
        '400':
          description: Bad request
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Already exists
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '422':
          description: Unprocessable Entity
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/entities/{entityId}':
    parameters:
      - $ref: '#/components/parameters/tenantHeader'
    get:
      description: Retrieve an specific Entity from an NGSI-LD system. It's possible to specify the Entity attributes to be retrieved by using query parameters
      operationId: retrieveEntityById
      tags:
        - Context Information
        - Entities
      parameters:
        - $ref: '#/components/parameters/entityId'
        - $ref: '#/components/parameters/attrs'
        - $ref: '#/components/parameters/parameters-type'
        - $ref: '#/components/parameters/options'
        - $ref: '#/components/parameters/link'
      responses:
        '200':
          description: OK
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Entity'
              examples:
                simple:
                  externalValue: 'http://localhost:8090/examples/Entity-example.json'
        '400':
          description: Bad request
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/entities/{entityId}/attrs/':
    parameters:
      - $ref: '#/components/parameters/tenantHeader'
    post:
      description: Append new Entity attributes to an existing Entity within an NGSI-LD system
      operationId: appendEntityAttrs
      tags:
        - Context Information
        - Entities
      parameters:
        - $ref: '#/components/parameters/entityId'
        - $ref: '#/components/parameters/parameters-options'
      requestBody:
        required: true
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/EntityFragment'
      responses:
        '204':
          description: No Content
        '207':
          description: Partial Success. Only the attributes included in the response payload were successfully appended
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/UpdateResult'
        '400':
          description: Bad request
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    patch:
      description: Update existing Entity attributes within an NGSI-LD system
      operationId: updateEntityAttrs
      tags:
        - Context Information
        - Entities
      parameters:
        - $ref: '#/components/parameters/entityId'
      requestBody:
        required: true
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/EntityFragment'
      responses:
        '204':
          description: No Content.
        '207':
          description: Partial Success. Only the attributes included in the response payload were successfully updated
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/UpdateResult'
        '400':
          description: Bad Request
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  parameters:
    id:
      name: id
      description: Comma separated list of URIs to be retrieved
      in: query
      required: false
      schema:
        type: string
    idPattern:
      name: idPattern
      description: Regular expression that must be matched by Entity ids
      in: query
      required: false
      schema:
        type: string
        format: regexp
    type:
      name: type
      description: Comma separated list of Entity type names to be retrieved
      in: query
      required: false
      schema:
        type: string
        minLength: 1
    attrs:
      name: attrs
      description: Comma separated list of attribute names (properties or relationships) to be retrieved
      in: query
      required: false
      schema:
        type: string
        minLength: 1
    q:
      name: q
      description: Query
      in: query
      required: false
      schema:
        type: string
        minLength: 1
    tenantHeader:
      name: NGSILD-Tenant
      in: header
      schema:
        type: string
        default: "orion"
      required: false
    coordinates:
      name: coordinates
      description: Coordinates serialized as a string
      in: query
      required: false
      schema:
        type: string
        minLength: 1
    geoproperty:
      name: geoproperty
      description: The name of the property that contains the geo-spatial data that will be used to resolve the geoquery
      in: query
      required: false
      schema:
        type: string
        minLength: 1
    csf:
      name: csf
      description: Context Source Filter
      in: query
      required: false
      schema:
        type: string
        minLength: 1
    limit:
      name: limit
      description: Pagination limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
    pageAnchor:
      name: pageAnchor
      description: Size of the page to be returned
      in: query
      required: false
      schema:
        type: string
        format: uri
    pageSize:
      name: pageSize
      description: Size of the page to be returned
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
    offset:
      name: offset
      description: Pagination offset
      in: query
      required: false
      schema:
        type: integer
        default: 0
    options:
      name: options
      description: Options dictionary
      in: query
      required: false
      schema:
        type: string
        enum:
          - keyValues
          - sysAttrs
    entityId:
      name: entityId
      description: Entity Id
      in: path
      required: true
      schema:
        type: string
        format: uri
    parameters-type:
      name: type
      description: Entity Type
      in: query
      required: false
      schema:
        type: string
    parameters-options:
      name: options
      description: Indicates that no attribute overwrite shall be performed
      in: query
      required: false
      schema:
        type: string
        enum:
          - noOverwrite
    attrId:
      name: attrId
      description: Attribute Id
      in: path
      required: true
      schema:
        type: string
    subscriptionId:
      name: subscriptionId
      description: Subscription Id
      in: path
      required: true
      schema:
        type: string
        format: uri
    registrationId:
      name: registrationId
      description: Registration Id
      in: path
      required: true
      schema:
        type: string
        format: uri
    link:
      name: Link
      description: Link header to be used as described in the json-ld spec.
      in: header
      required: false
      schema:
        type: string
    instanceId:
      name: instanceId
      description: Instance Id
      in: path
      required: true
      schema:
        type: string
        format: uri
  schemas:
    LdContext:
      type: object
    EntityFragment:
      type: object
      properties:
        '@context':
          $ref: '#/components/schemas/LdContext'
        id:
          type: string
          format: uri
      additionalProperties:
        type: object
    Entity:
      type: object
      properties:
        '@context':
          $ref: '#/components/schemas/LdContext'
        id:
          type: string
          format: uri
      additionalProperties:
        type: object
    EntityList:
      type: array
      items:
        $ref: '#/components/schemas/Entity'
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
      required:
        - type
    NotUpdatedDetails:
      type: object
      properties:
        attributeName:
          type: string
          pattern: ''
        reason:
          type: string
          minLength: 1
    UpdateResult:
      type: object
      properties:
        updated:
          type: array
          items:
            type: string
            pattern: ''
        notUpdated:
          type: array
          items:
            $ref: '#/components/schemas/NotUpdatedDetails'
