name: Integration-test

on:
  push

jobs:
  it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Run compose
        id: compose
        run: |
          docker-compose -f env/docker-compose.yaml up -d

      - name: Execute tests
        id: test
        run: |
          mvn clean test coveralls:jacoco -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }}